--- 
memory: "512"
disksize: "8096"
uri: "http://mirror.cisp.com/CentOS/6.3/isos/x86_64/CentOS-6.3-x86_64-minimal.iso"
name: "Puppet"
ostype: "RedHat_64"
iso: "CentOS-6.3-x86_64-minimal.iso"
bootwait: "10"
